### ISSUE TITLE
Cannot run `kitura init` or `kitura create` on MacOS

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/kitura-cli#4]
I get the following error:

```
kitura init
module.js:487
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
Error swiftserver --init 

You don’t seem to have a generator with the name “swiftserver” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-swiftserver.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
```

**Comment by gmosx** [comment]
Hmm, seems I had an older version of npm. Still maybe you would like to mention in the docs to update to the latest version of npm.

**Comment by ianpartridge** [comment]
Thanks, I've just opened #5 which should fix issues like this. Hopefully that will be merged soon.

**Comment by ianpartridge** [comment]
I've released `0.0.8` which should fix this and other similar issues. Thanks!

**Comment by MaximBazarov** [comment]
No, same issue in `0.0.8`
```
Command failed: /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js config get cache --parseable
module.js:515
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by ianpartridge** [comment]
What are these, please? `node -v`, `npm -v`, `npx -v`.

**Comment by ianpartridge** [comment]
And `npm list -g --depth=0`.

**Comment by MaximBazarov** [comment]
@ianpartridge 
```
node -v
v8.8.1
```

and 
```
npm -v
module.js:515
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

and 
```
npx -v
9.6.0
```

and 
```
npm list -g --depth=0
module.js:515
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by MaximBazarov** [comment]
Reinstalling `npm` solves this issue

**Comment by ianpartridge** [comment]
Good to hear - thanks.
